import type { Metadata } from "next";
import { Inter,Pompiere, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/SessionProvider";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";

const inter = Poppins({  weight: ["400"], style:["normal"],subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>

    
      <body className={inter.className}>
      <Header />
        {children}
        <Toaster />
        </body>
      </Providers>
    </html>
  );
}
